return {}

-- local actions = require("telescope.actions")
--
-- require("telescope").setup({
--   defaults = {
--     layout_strategy = "vertical",
--     mappings = {
--       i = {
--         ["esc"] = actions.close,
--       }
--     }
--   },
--   pickers = {
--     buffers = {
--       sort_lastused = true,
--       ignore_current_buffer = true,
--     }
--   },
-- })
--
-- local builtin = require("telescope.builtin")
-- vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
-- vim.keymap.set("n", "<leader>fg", builtin.live_grep, {})
-- vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
-- vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
-- vim.keymap.set("n", "<leader>rr", builtin.registers, {})
